### ISSUE TITLE
Optionally display the modifying user instead of the creator.

### ISSUE THREAD

**Issue by mbaechtold** [4teamwork/ftw.dashboard.portlets.recentlymodified#9]
The template used in the view `RecentlyModifiedView` displays the creator of the object (see https://github.com/4teamwork/ftw.dashboard.portlets.recentlymodified/blob/1.2.8/ftw/dashboard/portlets/recentlymodified/browser/templates/recently_modified_view.pt#L52).

But for some users it would be more useful if it would display the last user who modified the object. 

This should be configurable in the registry.

**Comment by jone** [comment]
The last modifier is not known in Plone.
For knowing the last modifier we could use [collective.lastmodifier](https://github.com/4teamwork/collective.lastmodifier/) though.
